### ISSUE TITLE
combineReducers is different than the original

### ISSUE THREAD

**Issue by jermahs** [johnpryan/redux.dart#12]
The idea behind `combineReducers` is for each reducer to control a specific piece of the state. Your version of `combineReducers` simply chains them over the same state instead of divvying up the state to be controlled by the individual reducers. 

See documentation: https://redux.js.org/docs/basics/Reducers.html

P.S., your redux port is far more readable than the others. 👍

**Comment by brianegan** [comment]
Hi @jpgilchrist, thanks for writing in! Glad you've found the library to be quite usable.

`combineReducers` is an interesting case for Dart -- in general, this library tries to encourage Strong / Static Typing in the State object. This means we recommend the State object be a Dart class with proper Type information.

The best way to compose state ala ReduxJS `combineReducers` is to do a bit more work in the main reducer function, which saves a lot of type casting later: https://github.com/johnpryan/redux.dart/issues/10#issuecomment-332593512

For `combineReducers` to work the way you're expecting, we'd have to require the State object simply be a `Map<String, Object>`. That means you'd lose all typing information on your State object, and require that you do a lot of Type Casting throughout your app. E.g. `store.state["todos"] as List<Todo>`. If someone changes the type of "todos" from `List<Todo>` to `DopeTodoList`, you could easily run into cast errors. In a strong-mode / typed world, you would immediately see the errors in your editor / using Dart Analyzer.

`combineReducers` works really well for JS, where essentially every Object (Including a redux State tree) is a `Map<String, Object>`, but I don't know if this is the best thing in Dart since you'd lose the type information.

I'd be open to hearing your opinion about this!

I can see a couple of solutions:

  1. Make it so `combineReducers` only works with a `Map<String, Object>`. We now have additional utilities called [`combineTypedReducers`](https://www.dartdocs.org/documentation/redux/2.0.2/redux/combineTypedReducers.html) and [`combineTypedMiddleware`](https://www.dartdocs.org/documentation/redux/2.0.2/redux/combineTypedMiddleware.html) for folks who want Strong typing, so this might be an option, but not my favorite personally.
  2. Use `combineReducers` the way it works now, and enforce Strong typing on the State object and write better docs to highlight how to compose large trees (This needs to happen anyhow)

What are your thoughts?

**Comment by jermahs** [comment]
@brianegan thanks for the quick reply. I'm actually fairly new to dart myself. I was drawn in by flutter and have just begun learning it. What you are saying makes complete sense and I came to the same conclusion myself after working with the library briefly and implemented my own `Map<String, Object>` combineReducer quite simply... It also doesn't look nearly as nice as the official ReduxJS implementation since dart doesn't have the syntactical sugar (or at least that I know of) `combineReducers({reducerOne, reducerTwo})`... `combineReducers({"reducerOne": reducerOne, "reducerTwo": reducerTwo})` just doesn't have the same appeal!

I am finding myself having to deal with an insane amount of type casting already and already determined that I need to get away from `Map<String, Object>` as the root object for my state. So, I'd opt fro option 2 as the best road going forward and wouldn't bother with option 1. 

I was wondering if you could direct me towards some more examples with respect to using a class as the state? It seems like it could get really cumbersome in a reducer to something like:

``` 
reducer(ApplicationState state, action) {
  ApplicationState _state = new ApplicationState();
  // what do I do about all the other internal state if I have several controlled states... 
  if (action.type == SomeAction) {
    _state.internalState = new InternalState(action.data);
   return _state; // this seems weird too (I'm probably doing this wrong)
  }
  return state;
}
```

As I'm new to dart and to this library, I'm sure I'm doing stuff wrong, but haven't found more "complex" examples. The increment, decrement on a contrived int state is obvious with your library... I'm having a harder time trying to figure out the best way to organize all this in a larger more complex scenario.

**Comment by jermahs** [comment]
@brianegan I did just read #10 and that helps A LOT! Having the constructor for AppState take the result of the reducers is incredibly clean and just makes sense. As you had mentioned there, that should be in the README and probably should be the premier example.

**Comment by brianegan** [comment]
Cool, thanks for the feedback! I wanted to make sure that example worked for peeps a bit more before writing up more docs for it, but it seems like the feedback on that pattern has been positive!

I'll write up more complete docs, and point to more complex examples of how to use Redux + Flutter, which can be found here:

One example can be found here: https://gitlab.com/brianegan/flutter_architecture_samples
Another similar thing here: https://github.com/xqwzts/flutter-redux-todo-list

I'll pop those in the Documentation as well.

Thanks again for writing in!

**Comment by jermahs** [comment]
@brianegan thanks. I must have been thinking about it while sleeping as I woke up with a concern about the pattern. If we are always returning a `new AppState(reducerOne, reducerTwo, ...)` isn't it possible that we end up with unnecessary re-processing of the build functions as it will always be different? It obviously, won't re-render due to the "VDOM" diff not being different, but all the build functions could re-run, right? 

In redux reducers (and in your simpler examples) you have the fallback option of:

```dart
reducerOne (state, action) {
  if (action.type === 'something') {
    return state + 1;
  }
  return state;
}
```

In our combined reducer example, we don't have that fallback, which is fine. I'm just trying to understand how that will interact with the `StoreConnector` and it's builder.

**Comment by brianegan** [comment]
Heya @jpgilchrist. Good catch! That is indeed one thing that could happen. Therefore, `flutter_redux` has a `StoreConnector` Widget that comes with an option that allows you to avoid rebuilding if the ViewModel hasn't changed. The option is called `distinct`. How does this work? You must implement the `==` method on your ViewModel classes, and use the `distinct` option in your `StoreConnector`.

Docs here: https://www.dartdocs.org/documentation/flutter_redux/0.3.2/flutter_redux/StoreConnector-class.html

Example of implementing this here: https://github.com/xqwzts/flutter-redux-todo-list/commit/d16f9735b53beea48dcc26c953a3b5ddf315d21b

**Comment by jermahs** [comment]
@brianegan ah, I was looking through the examples and had seen references to both `distinct` and the overide of the `==` operator in the state classes; now I understand 👍

**Comment by jordyvandomselaar** [comment]
@brianegan I know this issue is really old by now but I'd like to add a comment in here instead of creating a new issue for the sake of context.

Would it be possible to rename `combineReducers` to something else? Functionally it does something different than `combineReducers` from the original Redux. I get why it does it and I agree with the choices made in this package but when I googled "flutter_redux combine reducers" instead of coming to the conclusion that you should do it differently I ended up messing around for about a hour figuring out how `combineReducers` was gonna do what I wanted.

Props to this package and the docs, they're really clear (apart from the `combineReducers` thing)
