### ISSUE TITLE
Avoiding merge headaches

### ISSUE THREAD

**Issue by kentcb** [johnpryan/redux.dart#19]
Hi,

I'm fairly new to redux, and am trying to define an architecture that will allow different developers working on independent features to avoid stepping on each other's toes. Certainly, composing reducers helps in this regard, and the docs do a great job of explaining how to achieve that.

However, I don't think composing reducers is going to be enough to avoid merge conflict headaches. If feature A and feature B are worked on in tandem, that will require:

1. New `AppState.AState` and `AppState.BState` fields
2. New reducers for `AState` and `BState`
3. New middleware to handle asynchronous operations (for example) on behalf of both `AState` and `BState`
4. `AppState.hashCode` be updated
5. `AppState.operator ==` be updated
6. `AppState.toString` be updated

Composing reducers helps with point 2, but not the other points. Is there any guidance on avoiding conflicts and merge pain outside of reducers?

To be honest, I went looking for some kind of "composite state" support in redux, so you could do something like:

```dart
class AppState extends CompositeState {
  final List<ChildState> childState;

  AppState(List<ChildState> childState);
}

class FeatureA extends ChildState {};

class FeatureB extends ChildState {};
```
I couldn't find anything, so I tried spiking something, but it gets messy quite quickly. For the record (and for my future reference, as I'm about to can it) I ended up with:
```dart
@immutable
class AppState {
  final List<ChildStore<dynamic>> childStores;

  AppState.initial()
      : childStores = <ChildStore<dynamic>>[
          new LoginStore.initial(),
        ];

  AppState._withChildStores(this.childStores) : assert(childStores != null);

  AppState copyWith({List<ChildStore<dynamic>> childStores}) =>
      new AppState._withChildStores(childStores ?? this.childStores);

  State getChildState<State>() {
    for (var childStore in childStores) {
      if (childStore is ChildStore<State>) {
        return childStore.state;
      }
    }

    assert(false, "Failed to find child store of type ChildStore<$State>.");
    return null;
  }

  @override
  int get hashCode {
    var hash = 0;

    for (var childStore in childStores) {
      hash ^= childStore.hashCode;
    }

    return hash;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is AppState && listsEqual(childStores, other.childStores));

  @override
  String toString() => "AppState{childStores: $childStores}";
}

abstract class ChildStore<State> {
  State get state;

  ChildStore<State> withState(State state);

  bool canHandle(dynamic action);

  Reducer<State> getReducer();

  List<Middleware<State>> getMiddleware();
}
```
I gave up when I got the middleware stage because things are just getting too convoluted.

But you can see that such a mechanism would allow developers to work on independent features with only a single point of merge contention: the creation of the initial `AppState`. Any conflicts here would be trivial to resolve.

**Comment by brianegan** [comment]
Hey hey, good Q! I think you've generally got the right approach and have identified the right integration points. However, I'm a bit curious: Do you think there will be massive merge headaches for your team? 

I've worked with architectures like this before on decent sized feature teams, but I haven't personally experienced a ton of merge pain.

  * Combine your reducers with `combineTypedReducers`, each feature package will add their reducers to a list, each on their own line. If two Pull Requests add to the end of the list, you might need to resolve this, but it would be as simple as keeping both definitions.
  * Combine Middleware with `combineTypedMiddleware`. Same scenario as Reducers.
  * Updating State object: This could involve modifying three lines, but as long as each part of your HashCode, Equals, and toString is on it's own line, it should once again be a clean merge / easy conflict resolution. Thinking of a hash function that looks like this: https://github.com/brianegan/flutter_architecture_samples/blob/master/example/redux/lib/models/app_state.dart#L34.
  * For State objects, you could also consider using `built_value`: it would generate the hashCode, Equals, and ToString methods for ya.

Overall, I feel like Merge Conflicts are always a possibility at integration points, whether it's a Redux Store, a Config File, Rollout Flags, Java Dagger Modules, etc, but I feel like these are relatively straight-forward conflicts to resolve.

Let me know if you vibe with this at all, or if it's not making a ton of sense :) I always find Merge Conflict headaches come from merging a feature branch into a master that has seen larger refactors, rather than from Adding / Removing a few lines at an integration point such as a Config File or Redux Store, so perhaps I'm not feeling the pain!

**Comment by brianegan** [comment]
@kentcb Mind if I close this for now? Happy to discuss further if need be :)

**Comment by kentcb** [comment]
Ah, sorry forgot to close this myself. Yes, now that I've implemented a few features I can see how merge conflicts would only occur in my `AppState`, and then would only be trivial to resolve. Thanks Brian!
