### ISSUE TITLE
Compatible with Redux Devtools?

### ISSUE THREAD

**Issue by andresaraujo** [johnpryan/redux.dart#2]
It would be great if redux dart is compatible to redux devtools like https://github.com/zalmoxisus/redux-devtools-extension

**Comment by johnpryan** [comment]
Interesting idea - At first glance, I think this would be challenging because this would (I think) require Actions and State to only support objects that extend JsProxy (using the new `package:js` interop)

I haven't given it much thought but I suppose it wouldn't be too hard to write a dart version of the dev tools...

**Comment by brianegan** [comment]
As a heads up, I've just written some native Redux.dart dev tools on my machine. I'm adding docs and cleaning them up a bit, and will publish the results soon!

**Comment by MichaelMarner** [comment]
I've been doing some experimenting with getting this project working with the [Javascript Remote Devtools](https://github.com/zalmoxisus/remote-redux-devtools)

Going from Dart (Flutter) to remote devtools is not too difficult, and time travel should also be possible as well. Not sure how to handle arbitrary actions from Javascript => Dart, but I'm also not up to that.

But here's the Counter demo app working, it's a start:

https://youtu.be/z4Wwc11QXDM

**Comment by MichaelMarner** [comment]
Something ready enough to share now:

https://github.com/MichaelMarner/dart-redux-remote-devtools
